### ISSUE TITLE
Menu System

### ISSUE THREAD

**Issue by jserrao** [jserrao/modern-trousseau-gatsby#186]
This task is for getting the regular and mobile menus to work properly. There are a number of errors now.

**Comment by jserrao** [comment]
Deeper explanation @Cherezmz :

- Get rid of gray bar menu on desktop
- Make the mobile menu hamburger icon in the gray bar work by adding in some Javascript 
- Fix the oversized fonts on the mobile and desktop pink menus - Jenny says font size should be about 18-20px
- On the mobile pink menu, make the item separators look more like the original design
- On the mobile gray menu, make the right icon the map icon and link it to the `/locations` page

**Comment by Cherezmz** [comment]
Get rid of gray bar menu on desktop - **done**. NavBar was added in each page, Thus, it should be deleted from every page but I did not touch other pages. 

Make the mobile menu hamburger icon in the gray bar work by adding in some Javascript
Should hamburger icon work? We see all the menu items anyway. Why we need to make it twice? 
**Done**: changed three lines of the hamburger menu to the location icon.

Fix the oversized fonts on the mobile and desktop pink menus - Jenny says font size should be about 18-20px - **done** for mobile menu. need to double check with the desktop because the font size does not seem big 

On the mobile pink menu, make the item separators look more like the original design - **done**. I deleted the dots using media query but need to define the breakpoint 

On the mobile gray menu, make the right icon the map icon and link it to the /locations page
Do we really need the gray menu in the mobile version?

**Comment by jserrao** [comment]
@Cherezmz -

Gray bar is just for mobile now.
We only need one hamburger menu, for the pink menu.
I don't think we need the gray menu - just use the pink menu on mobile.

Thanks for the hard work.

**Comment by jserrao** [comment]
I assume you'll be adding more to the #199 PR, right @Cherezmz? I wont merge it yet if so.

**Comment by Cherezmz** [comment]
@jserrao 

yes
