### ISSUE TITLE
Implement Appointment Model into Gatsby

### ISSUE THREAD

**Issue by jcasado6** [jserrao/modern-trousseau-gatsby#47]

**Comment by jserrao** [comment]
@jcasado6 - I'm going to make you lead on the booking stuff. The issue is that each booking is getting created inside Gatsby and the client doesn't want it saved - we're just going to output it as an email I think. Still waiting clarification on that but we don't need to model in Contentful.

If you could post the model you made in this ticket, we can talk about implementation approaches.

**Comment by jserrao** [comment]
Appointment Model but we probably dont need it
https://app.contentful.com/spaces/2n4rer1mpqy8/content_types/appointment/fields
